### PR TITLE
Install icons and .desktop files

### PR DESCRIPTION
**Pull request by Mailaender**
similar to solarus-games/solarus#1021.

### CODE REVIEW

**Comment by Mailaender** [comment]
See https://build.opensuse.org/request/show/452808 for an integration test. Not sure if you are overdoing it with 768px and 1024px. Maybe add a `.svg` file instead.

**Comment by oclero** [comment]
@Mailaender 
Since all the games logos/icons are vector, I can give a svg file for each. The 1024px size was used for generating Mac OS icon (icns file).
So what files are needed for OpenSuse? (and what are the sizes for the SVG?)

**Comment by Mailaender** [comment]
I think the Linux desktop auto-scale or generate cached PNGs themselves if you just put an SVG in the appropriate `/usr/share/icons/hicolor/scalable/apps/` folder.

**Comment by oclero** [comment]
OK. The thing is some sizes are optimized for the size they're intended to bu displayed (example: the 16*16px icon is pixel perfect, so a bit customized in order to appear better, and does not really correspond to the bigger sizes. Do you know if it is possible to give something like this:
 - PNG files for the small sizes, to be pixel perfect (16 to 32px)
 - An SVG file for the other sizes (bigger than the small ones)

**Comment by christopho** [comment]
We can add an SVG icon while keeping all PNG variants.

**Comment by oclero** [comment]
Perfect! I'll create the issue and assign myself on it.

**Comment by Mailaender** [comment]
Yes, I think the manual PNGs are exactly for the case where auto-scaling isn't enough or when you create variants of the symbol with fewer details etc.

**Comment by oclero** [comment]
@Mailaender I created the needed files. What to do next? https://github.com/solarus-games/solarus-quest-editor/issues/265

**Comment by Mailaender** [comment]
Copy it into https://github.com/solarus-games/solarus-quest-editor/tree/dev/images/icon and setup an install rule like I did in this pull request.

**Comment by oclero** [comment]
Ok thanks!

**Pull request merged**
